/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeebcentralChapterIdRouteImport } from './routes/weebcentral.$chapterId'
import { Route as WeebcentralSeriesSeriesIdRouteImport } from './routes/weebcentral-series.$seriesId'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as ReaderChapterIdRouteImport } from './routes/reader.$chapterId'
import { Route as ApiUploadRouteImport } from './routes/api.upload'
import { Route as ApiSeriesRouteImport } from './routes/api.series'
import { Route as V1WeebcentralSeriesRouteImport } from './routes/v1.weebcentral.series'
import { Route as V1WeebcentralChapterRouteImport } from './routes/v1.weebcentral.chapter'
import { Route as V1UploadChapterRouteImport } from './routes/v1.upload.chapter'
import { Route as V1ImageB64RouteImport } from './routes/v1.image.$b64'
import { Route as ApiSeriesSeriesIdRouteImport } from './routes/api.series.$seriesId'
import { Route as ApiChapterChapterIdRouteImport } from './routes/api.chapter.$chapterId'
import { Route as V1LocalChapterIdFilenameRouteImport } from './routes/v1.local.$chapterId.$filename'
import { Route as ApiImageChapterIdPageIndexRouteImport } from './routes/api.image.$chapterId.$pageIndex'
import { Route as ApiChapterChapterIdProgressRouteImport } from './routes/api.chapter.$chapterId.progress'
import { Route as ApiChapterChapterIdPagePageIndexRouteImport } from './routes/api.chapter.$chapterId.page.$pageIndex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeebcentralChapterIdRoute = WeebcentralChapterIdRouteImport.update({
  id: '/weebcentral/$chapterId',
  path: '/weebcentral/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const WeebcentralSeriesSeriesIdRoute =
  WeebcentralSeriesSeriesIdRouteImport.update({
    id: '/weebcentral-series/$seriesId',
    path: '/weebcentral-series/$seriesId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderChapterIdRoute = ReaderChapterIdRouteImport.update({
  id: '/reader/$chapterId',
  path: '/reader/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeriesRoute = ApiSeriesRouteImport.update({
  id: '/api/series',
  path: '/api/series',
  getParentRoute: () => rootRouteImport,
} as any)
const V1WeebcentralSeriesRoute = V1WeebcentralSeriesRouteImport.update({
  id: '/v1/weebcentral/series',
  path: '/v1/weebcentral/series',
  getParentRoute: () => rootRouteImport,
} as any)
const V1WeebcentralChapterRoute = V1WeebcentralChapterRouteImport.update({
  id: '/v1/weebcentral/chapter',
  path: '/v1/weebcentral/chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const V1UploadChapterRoute = V1UploadChapterRouteImport.update({
  id: '/v1/upload/chapter',
  path: '/v1/upload/chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ImageB64Route = V1ImageB64RouteImport.update({
  id: '/v1/image/$b64',
  path: '/v1/image/$b64',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeriesSeriesIdRoute = ApiSeriesSeriesIdRouteImport.update({
  id: '/$seriesId',
  path: '/$seriesId',
  getParentRoute: () => ApiSeriesRoute,
} as any)
const ApiChapterChapterIdRoute = ApiChapterChapterIdRouteImport.update({
  id: '/api/chapter/$chapterId',
  path: '/api/chapter/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1LocalChapterIdFilenameRoute =
  V1LocalChapterIdFilenameRouteImport.update({
    id: '/v1/local/$chapterId/$filename',
    path: '/v1/local/$chapterId/$filename',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiImageChapterIdPageIndexRoute =
  ApiImageChapterIdPageIndexRouteImport.update({
    id: '/api/image/$chapterId/$pageIndex',
    path: '/api/image/$chapterId/$pageIndex',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChapterChapterIdProgressRoute =
  ApiChapterChapterIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => ApiChapterChapterIdRoute,
  } as any)
const ApiChapterChapterIdPagePageIndexRoute =
  ApiChapterChapterIdPagePageIndexRouteImport.update({
    id: '/page/$pageIndex',
    path: '/page/$pageIndex',
    getParentRoute: () => ApiChapterChapterIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/series': typeof ApiSeriesRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/weebcentral-series/$seriesId': typeof WeebcentralSeriesSeriesIdRoute
  '/weebcentral/$chapterId': typeof WeebcentralChapterIdRoute
  '/api/chapter/$chapterId': typeof ApiChapterChapterIdRouteWithChildren
  '/api/series/$seriesId': typeof ApiSeriesSeriesIdRoute
  '/v1/image/$b64': typeof V1ImageB64Route
  '/v1/upload/chapter': typeof V1UploadChapterRoute
  '/v1/weebcentral/chapter': typeof V1WeebcentralChapterRoute
  '/v1/weebcentral/series': typeof V1WeebcentralSeriesRoute
  '/api/chapter/$chapterId/progress': typeof ApiChapterChapterIdProgressRoute
  '/api/image/$chapterId/$pageIndex': typeof ApiImageChapterIdPageIndexRoute
  '/v1/local/$chapterId/$filename': typeof V1LocalChapterIdFilenameRoute
  '/api/chapter/$chapterId/page/$pageIndex': typeof ApiChapterChapterIdPagePageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/series': typeof ApiSeriesRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/weebcentral-series/$seriesId': typeof WeebcentralSeriesSeriesIdRoute
  '/weebcentral/$chapterId': typeof WeebcentralChapterIdRoute
  '/api/chapter/$chapterId': typeof ApiChapterChapterIdRouteWithChildren
  '/api/series/$seriesId': typeof ApiSeriesSeriesIdRoute
  '/v1/image/$b64': typeof V1ImageB64Route
  '/v1/upload/chapter': typeof V1UploadChapterRoute
  '/v1/weebcentral/chapter': typeof V1WeebcentralChapterRoute
  '/v1/weebcentral/series': typeof V1WeebcentralSeriesRoute
  '/api/chapter/$chapterId/progress': typeof ApiChapterChapterIdProgressRoute
  '/api/image/$chapterId/$pageIndex': typeof ApiImageChapterIdPageIndexRoute
  '/v1/local/$chapterId/$filename': typeof V1LocalChapterIdFilenameRoute
  '/api/chapter/$chapterId/page/$pageIndex': typeof ApiChapterChapterIdPagePageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/series': typeof ApiSeriesRouteWithChildren
  '/api/upload': typeof ApiUploadRoute
  '/reader/$chapterId': typeof ReaderChapterIdRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/weebcentral-series/$seriesId': typeof WeebcentralSeriesSeriesIdRoute
  '/weebcentral/$chapterId': typeof WeebcentralChapterIdRoute
  '/api/chapter/$chapterId': typeof ApiChapterChapterIdRouteWithChildren
  '/api/series/$seriesId': typeof ApiSeriesSeriesIdRoute
  '/v1/image/$b64': typeof V1ImageB64Route
  '/v1/upload/chapter': typeof V1UploadChapterRoute
  '/v1/weebcentral/chapter': typeof V1WeebcentralChapterRoute
  '/v1/weebcentral/series': typeof V1WeebcentralSeriesRoute
  '/api/chapter/$chapterId/progress': typeof ApiChapterChapterIdProgressRoute
  '/api/image/$chapterId/$pageIndex': typeof ApiImageChapterIdPageIndexRoute
  '/v1/local/$chapterId/$filename': typeof V1LocalChapterIdFilenameRoute
  '/api/chapter/$chapterId/page/$pageIndex': typeof ApiChapterChapterIdPagePageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/series'
    | '/api/upload'
    | '/reader/$chapterId'
    | '/series/$seriesId'
    | '/weebcentral-series/$seriesId'
    | '/weebcentral/$chapterId'
    | '/api/chapter/$chapterId'
    | '/api/series/$seriesId'
    | '/v1/image/$b64'
    | '/v1/upload/chapter'
    | '/v1/weebcentral/chapter'
    | '/v1/weebcentral/series'
    | '/api/chapter/$chapterId/progress'
    | '/api/image/$chapterId/$pageIndex'
    | '/v1/local/$chapterId/$filename'
    | '/api/chapter/$chapterId/page/$pageIndex'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/series'
    | '/api/upload'
    | '/reader/$chapterId'
    | '/series/$seriesId'
    | '/weebcentral-series/$seriesId'
    | '/weebcentral/$chapterId'
    | '/api/chapter/$chapterId'
    | '/api/series/$seriesId'
    | '/v1/image/$b64'
    | '/v1/upload/chapter'
    | '/v1/weebcentral/chapter'
    | '/v1/weebcentral/series'
    | '/api/chapter/$chapterId/progress'
    | '/api/image/$chapterId/$pageIndex'
    | '/v1/local/$chapterId/$filename'
    | '/api/chapter/$chapterId/page/$pageIndex'
  id:
    | '__root__'
    | '/'
    | '/api/series'
    | '/api/upload'
    | '/reader/$chapterId'
    | '/series/$seriesId'
    | '/weebcentral-series/$seriesId'
    | '/weebcentral/$chapterId'
    | '/api/chapter/$chapterId'
    | '/api/series/$seriesId'
    | '/v1/image/$b64'
    | '/v1/upload/chapter'
    | '/v1/weebcentral/chapter'
    | '/v1/weebcentral/series'
    | '/api/chapter/$chapterId/progress'
    | '/api/image/$chapterId/$pageIndex'
    | '/v1/local/$chapterId/$filename'
    | '/api/chapter/$chapterId/page/$pageIndex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSeriesRoute: typeof ApiSeriesRouteWithChildren
  ApiUploadRoute: typeof ApiUploadRoute
  ReaderChapterIdRoute: typeof ReaderChapterIdRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  WeebcentralSeriesSeriesIdRoute: typeof WeebcentralSeriesSeriesIdRoute
  WeebcentralChapterIdRoute: typeof WeebcentralChapterIdRoute
  ApiChapterChapterIdRoute: typeof ApiChapterChapterIdRouteWithChildren
  V1ImageB64Route: typeof V1ImageB64Route
  V1UploadChapterRoute: typeof V1UploadChapterRoute
  V1WeebcentralChapterRoute: typeof V1WeebcentralChapterRoute
  V1WeebcentralSeriesRoute: typeof V1WeebcentralSeriesRoute
  ApiImageChapterIdPageIndexRoute: typeof ApiImageChapterIdPageIndexRoute
  V1LocalChapterIdFilenameRoute: typeof V1LocalChapterIdFilenameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weebcentral/$chapterId': {
      id: '/weebcentral/$chapterId'
      path: '/weebcentral/$chapterId'
      fullPath: '/weebcentral/$chapterId'
      preLoaderRoute: typeof WeebcentralChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weebcentral-series/$seriesId': {
      id: '/weebcentral-series/$seriesId'
      path: '/weebcentral-series/$seriesId'
      fullPath: '/weebcentral-series/$seriesId'
      preLoaderRoute: typeof WeebcentralSeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$chapterId': {
      id: '/reader/$chapterId'
      path: '/reader/$chapterId'
      fullPath: '/reader/$chapterId'
      preLoaderRoute: typeof ReaderChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/series': {
      id: '/api/series'
      path: '/api/series'
      fullPath: '/api/series'
      preLoaderRoute: typeof ApiSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/weebcentral/series': {
      id: '/v1/weebcentral/series'
      path: '/v1/weebcentral/series'
      fullPath: '/v1/weebcentral/series'
      preLoaderRoute: typeof V1WeebcentralSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/weebcentral/chapter': {
      id: '/v1/weebcentral/chapter'
      path: '/v1/weebcentral/chapter'
      fullPath: '/v1/weebcentral/chapter'
      preLoaderRoute: typeof V1WeebcentralChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/upload/chapter': {
      id: '/v1/upload/chapter'
      path: '/v1/upload/chapter'
      fullPath: '/v1/upload/chapter'
      preLoaderRoute: typeof V1UploadChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/image/$b64': {
      id: '/v1/image/$b64'
      path: '/v1/image/$b64'
      fullPath: '/v1/image/$b64'
      preLoaderRoute: typeof V1ImageB64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/series/$seriesId': {
      id: '/api/series/$seriesId'
      path: '/$seriesId'
      fullPath: '/api/series/$seriesId'
      preLoaderRoute: typeof ApiSeriesSeriesIdRouteImport
      parentRoute: typeof ApiSeriesRoute
    }
    '/api/chapter/$chapterId': {
      id: '/api/chapter/$chapterId'
      path: '/api/chapter/$chapterId'
      fullPath: '/api/chapter/$chapterId'
      preLoaderRoute: typeof ApiChapterChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/local/$chapterId/$filename': {
      id: '/v1/local/$chapterId/$filename'
      path: '/v1/local/$chapterId/$filename'
      fullPath: '/v1/local/$chapterId/$filename'
      preLoaderRoute: typeof V1LocalChapterIdFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$chapterId/$pageIndex': {
      id: '/api/image/$chapterId/$pageIndex'
      path: '/api/image/$chapterId/$pageIndex'
      fullPath: '/api/image/$chapterId/$pageIndex'
      preLoaderRoute: typeof ApiImageChapterIdPageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chapter/$chapterId/progress': {
      id: '/api/chapter/$chapterId/progress'
      path: '/progress'
      fullPath: '/api/chapter/$chapterId/progress'
      preLoaderRoute: typeof ApiChapterChapterIdProgressRouteImport
      parentRoute: typeof ApiChapterChapterIdRoute
    }
    '/api/chapter/$chapterId/page/$pageIndex': {
      id: '/api/chapter/$chapterId/page/$pageIndex'
      path: '/page/$pageIndex'
      fullPath: '/api/chapter/$chapterId/page/$pageIndex'
      preLoaderRoute: typeof ApiChapterChapterIdPagePageIndexRouteImport
      parentRoute: typeof ApiChapterChapterIdRoute
    }
  }
}

interface ApiSeriesRouteChildren {
  ApiSeriesSeriesIdRoute: typeof ApiSeriesSeriesIdRoute
}

const ApiSeriesRouteChildren: ApiSeriesRouteChildren = {
  ApiSeriesSeriesIdRoute: ApiSeriesSeriesIdRoute,
}

const ApiSeriesRouteWithChildren = ApiSeriesRoute._addFileChildren(
  ApiSeriesRouteChildren,
)

interface ApiChapterChapterIdRouteChildren {
  ApiChapterChapterIdProgressRoute: typeof ApiChapterChapterIdProgressRoute
  ApiChapterChapterIdPagePageIndexRoute: typeof ApiChapterChapterIdPagePageIndexRoute
}

const ApiChapterChapterIdRouteChildren: ApiChapterChapterIdRouteChildren = {
  ApiChapterChapterIdProgressRoute: ApiChapterChapterIdProgressRoute,
  ApiChapterChapterIdPagePageIndexRoute: ApiChapterChapterIdPagePageIndexRoute,
}

const ApiChapterChapterIdRouteWithChildren =
  ApiChapterChapterIdRoute._addFileChildren(ApiChapterChapterIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSeriesRoute: ApiSeriesRouteWithChildren,
  ApiUploadRoute: ApiUploadRoute,
  ReaderChapterIdRoute: ReaderChapterIdRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  WeebcentralSeriesSeriesIdRoute: WeebcentralSeriesSeriesIdRoute,
  WeebcentralChapterIdRoute: WeebcentralChapterIdRoute,
  ApiChapterChapterIdRoute: ApiChapterChapterIdRouteWithChildren,
  V1ImageB64Route: V1ImageB64Route,
  V1UploadChapterRoute: V1UploadChapterRoute,
  V1WeebcentralChapterRoute: V1WeebcentralChapterRoute,
  V1WeebcentralSeriesRoute: V1WeebcentralSeriesRoute,
  ApiImageChapterIdPageIndexRoute: ApiImageChapterIdPageIndexRoute,
  V1LocalChapterIdFilenameRoute: V1LocalChapterIdFilenameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
